name: End-to-end tests

on:
  push:
    # branches: [ "main", "develop" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: run project
        run: npm run start

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
